config/routes.rb
Mmjv::Application.routes.draw do
  #resources :suppliers do
  #  resources :products
  #end

  #resources :product_types do
  #  resources :products
  #end
  #resources :product_types
  resources :products do
    #collection do
    #  get 'product_type'
    #end
  end

  resources :product_types

  devise_for :users


  resources :imgs, :only => [:destroy]



  root 'products#index'

end

app/models/img.rb
class Img < ActiveRecord::Base
  belongs_to :has_img, :polymorphic => true
  mount_uploader :image, ImageUploader
end

#module Img::Handler
#  def initialize
#    has_many :images, as: has_image
#    super
#  end
#end

app/models/product.rb
module ImgHandler
  def imgs=(image_array)
    image_array.each do |i|
      img = Img.new
      img.image = i
      imgs << img
    end
  end
  #
  #def imgs
  #  imgs.each{ |i| i.image }
  #end
end

class Product < ActiveRecord::Base
  use_farm_slugs

  include ImgHandler
  has_many :imgs, :as => 'has_img', :dependent => :destroy

  belongs_to :supplier
  validates :supplier_id, :presence => true

  belongs_to :product_type
  validates :product_type_id, presence: true

  #validates :name, presence: true

  validates :donation, presence: true, numericality: {:greater_than_or_equal_to => 0}

  validates :donation_owed, presence: true, numericality: {:greater_than_or_equal_to => 0}

  validates :quantity, presence: true, presence: true, numericality: {:greater_than_or_equal_to => 0} #default 0

  PRODUCT_TYPES = %w|flower|
  def self.types
    PRODUCT_TYPES
  end

  def self.products_hash
    p = Product.group_records(self.all, :product_type)
    a = p.sort_by{ |k, v| k.menu_index }
    h = {}
    a.each do |i|
      h[i[0]] = i[1]
    end
    h
  end



end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  validates :name, presence: true

  has_many :products
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  belongs_to :user
  has_many :products

  validates :name, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :supplier
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/imgs_controller.rb
class ImgsController < ApplicationController
  before_action :set_img, :only => [:destroy]

  respond_to :js

  def destroy
    obj = @img.has_img
    @img.destroy
    @imgs = obj.imgs
  end

  private

  def set_img
     @img = Img.find(params[:id])
  end
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @product_types = ProductType.all
    respond_with(@product_types)
  end

  def show
    @products = @product_type.products
    respond_with(@product_type)
  end

  def new
    @product_type = ProductType.new
    respond_with(@product_type)
  end

  def edit
  end

  def create
    @product_type = ProductType.new(product_type_params)
    @product_type.save
    respond_with(@product_type)
  end

  def update
    @product_type.update(product_type_params)
    respond_with(@product_type)
  end

  def destroy
    @product_type.destroy
    respond_with(@product_type)
  end

  private
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    def product_type_params
      params.require(:product_type).permit(:name, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  #before_action :set_product_type, only: [:index]

  respond_to :html

  def index
    @products = Product.all
    @products_hash = Product.products_hash
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :batch_description, :product_type_id, :thc, :cbd, :butane,
                                      {:imgs => []}, :remote_imgs_url, :imgs_cache,
                                       :donation, :quantity, :supplier_id, :donation_owed)
    end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @suppliers = Supplier.all
    respond_with(@suppliers)
  end

  def show
    respond_with(@supplier)
  end

  def new
    @supplier = Supplier.new
    respond_with(@supplier)
  end

  def edit
  end

  def create
    @supplier = Supplier.new(supplier_params)
    @supplier.save
    respond_with(@supplier)
  end

  def update
    @supplier.update(supplier_params)
    respond_with(@supplier)
  end

  def destroy
    @supplier.destroy
    respond_with(@supplier)
  end

  private
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    def supplier_params
      params.require(:supplier).permit(:name, :phone, :email, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Parts
  include HtmlTools

  def user_is_admin?
    current_user.admin if user_signed_in?
  end

  #----------------------Twitter Bootstrap----------------------------------------
  def error_row(record)
    html = '<div class="row"><div class="col-sm-12">'
    html += error_explanation(record)
    html += '</div></div>'
    html.html_safe
  end

  def bootstrap_text_field(attr, form_builder, media_query: 'sm', col_span: 4, alt_label: nil)
    html = bootstrap_form_col(media_query, col_span) do
      str = form_builder.label attr, alt_label, :class => 'form-label'
      str += form_builder.text_field attr, :class => 'form-control'
      str
    end
    html.html_safe
  end

  def bootstrap_text_area(attr, form_builder, media_query: 'sm', rows: 6, col_span: 4, alt_label: nil)
    html = bootstrap_form_col(media_query, col_span) do
      str = form_builder.label attr, alt_label, :class => 'form-label'
      str += form_builder.text_area attr, :class => 'form-control', :rows => rows
      str
    end
    html.html_safe
  end

  def bootstrap_select(attr, form_builder, options, media_query: 'sm', col_span: 4, alt_label: nil)
    html = bootstrap_form_col(media_query, col_span) do
      str = form_builder.label attr, alt_label, :class => 'form-label'
      str += form_builder.select attr, options, {}, :class => 'form-control'
      str
    end
    html.html_safe
  end

  def bootstrap_file_field(attr, form_builder, media_query: 'sm', col_span: 4, alt_label: nil)
    #html =
  end

  def bootstrap_submit_row(form_builder)
    html = '<div class="row"><div class="col-sm-12"><div class="form-group">'
    html += form_builder.submit :class => 'btn btn-primary'
    html += '</div></div></div>'
    html.html_safe
  end

  private

  def bootstrap_form_col(media_query, col_span, &block)
    html = %Q|<div class="col-#{media_query}-#{col_span}">|
    html += '<div class="form-group">'
    html += capture(&block)
    html += '</div></div>'
    html
  end
end

app/helpers/imgs_helper.rb
module ImgsHelper
  def img_list(imgs, version: :thumb)
    render :partial => 'imgs/image_list', :locals => {:imgs => imgs, :version => version}
  end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def display_thc(product)
    product.thc.blank? ? 'untested' : number_to_percentage(product.thc, :precision => 1)
  end

  def display_cbd(product)
    product.cbd.blank? ? 'untested' : number_to_percentage(product.cbd, :precision => 1)
  end

  def display_butane(product)
    product.butane.blank? ? 'n/a' : number_with_precision(product.butane, :precision => 2)
  end

end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/imgs/_image_list.html.erb
<div id="image_list">
  <% imgs.each do |i| %>
    <%= link_to i.image.url, :target => '_blank' do %>
      <%= image_tag i.image.url(version) %>
    <% end %>

    <!--<div>-->
    <%= link_to('delete', img_path(i), :remote => true, :method => :delete, :class => 'text-danger') if i.id %>

    <!--</div>-->
  <% end %>
</div>

app/views/imgs/destroy.js.erb
$('#image_list').replaceWith('<%= j render :partial => 'imgs/image_list', :locals => {:imgs => @imgs} %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medical Marijuana Vendors</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <%= favicon_link_tag "favicon.ico" %>
</head>
<body>

<%= render :partial => 'parts/top_nav' %>
<%= render :partial => 'parts/the_flash' %>

<div id="page_content">
  <%= yield %>
</div>

<%= render :partial => 'parts/footer' %>

</body>
</html>

app/views/parts/_footer.html.erb
<div id="page_footer">

</div>

app/views/parts/_multi_image_select.html.erb
<div class="col-md-6">
  <div class="form-group">
    <%= f.label uploader, :class => 'control-label' %>
    <%= f.file_field uploader, :class => 'form-control' %>
    <%= f.hidden_field "#{uploader}_cache".to_sym %>
  </div>

  <div class="form-group">
    <%= f.label "remote_#{uploader.to_s}_url".to_sym, 'or image URL', :class => 'control-label' %>
    <%= f.text_field "remote_#{uploader.to_s}_url".to_sym, :class => 'form-control' %>
  </div>
</div>

<div class="col-md-4 col-md-offset-2">
  <% if object.send(uploader).file %>
    <%= image_tag object.send(uploader).url(version) %>
  <% end %>
</div>

app/views/parts/_the_flash.html.erb
<div id="the_flash" class="text-center">
  <% if alert %>
    <div class="alert alert-danger">
      <h4><%= alert %></h4>
    </div>
  <% end %>
  <% if notice %>
    <div class="alert alert-success">
      <h4><%= notice %></h4>
    </div>

  <% end %>

  <script>
    $('#the_flash').delay(4000).slideUp(1000);
  </script>
</div>

app/views/parts/_top_nav.html.erb
<style>
  body{
    padding-top: 50px;
  }
</style>

<div id='top_nav' class='navbar navbar-fixed-top navbar-default navbar-inverse' role='navigation'>
  <div class="container">
    <div class='navbar-header'>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top_nav_body">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Medical Marijuana Vendors", root_path, :class => 'navbar-brand' %>
    </div>

    <div id='top_nav_body' class='collapse navbar-collapse'>
      <ul class='nav navbar-nav navbar-right'>
        <li>
          <%= link_to 'Products', products_path %>
        </li>

        <%# if user_is_admin? %>
          <!--<li class="dropdown">-->
            <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>-->
            <!--<ul class="dropdown-menu">-->
              <!--<li><%#= link_to 'All', products_path %></li>-->
              <!--<%# ProductType.all.each do |pt| %>-->
                <!--<%#= content_tag :li do %>-->
                  <!--<%#= link_to pt.name, product_type_path(pt)  %>-->
                  <!--<%#= link_to pt.name, products_path(:anchor => pt.name) %>-->
                <!--<%# end %>-->
              <!--<%# end %>-->
            <!--</ul>-->
          <!--</li>-->
        <%# end %>

        </li>

        <% if user_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Login', new_user_session_path %>
          </li>
          <!--<li style="font-weight:800;">-->
          <!--<%#= link_to 'Sign Up', new_user_registration_path %>-->
          <!--</li>-->
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing product_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<h1>Listing product_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |product_type| %>
      <tr>
        <td><%= product_type.name %></td>
        <td><%= product_type.description %></td>
        <td><%= link_to 'Show', product_type %></td>
        <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
        <td><%= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New product_type</h1>

<%= render 'form' %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product_type.description %>
</p>

<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>

app/views/products/_form.html.erb
<div class="product_form form_block">
  <%= form_for(@product, :multipart => true) do |f| %>
    <%= error_row(@product) %>

    <%= content_tag :div, :class => 'row' do %>
      <%= bootstrap_text_field :name, f %>
      <%= bootstrap_select :product_type_id, f, for_select(ProductType.all, :name, :id) %>
      <%= bootstrap_select :supplier_id, f, for_select(Supplier.all, :name, :id) %>
    <% end %>



    <%= content_tag :div, :class => 'row' do %>
      <%= bootstrap_text_field :thc, f, alt_label: 'THC Concentration' %>
      <%= bootstrap_text_field :cbd, f, alt_label: 'CBD Concentration' %>
      <%= bootstrap_text_field :butane, f, alt_label: 'Butane Concentration' %>
    <% end %>

    <%= content_tag :div, class: 'row' do %>
      <%= bootstrap_text_area :description, f, col_span: 6 %>
      <%= bootstrap_text_area :batch_description, f, col_span: 6 %>

    <% end %>

    <div class="row well">
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :imgs, 'Images', class: 'control-label' %>
          <%= f.file_field :imgs, :multiple => true, :class => 'form-control' %>
        </div>

        <!--<div class="form-group">-->
          <%#= f.label :remote_imgs_url, :class => 'control-label' %>
          <%#= f.text_field :remote_imgs_url, :class => 'form-control' %>
        <!--</div>-->
      </div><!-- col -->

      <div class="col-sm-8">
        <%= img_list @product.imgs %>

      </div><!-- col -->

    </div><!-- row -->

    <%= content_tag :div, class: 'row' do %>
      <%= bootstrap_text_field :donation, f, :alt_label => 'Donation Amount <small>per pound</small>'.html_safe %>
      <%= bootstrap_text_field :quantity, f, :alt_label => 'Quantity <small>in pounds</small>'.html_safe %>
      <%= bootstrap_text_field :donation_owed, f, :alt_label => 'Donation Owed <small>per pound</small>'.html_safe %>
    <% end %>


    <%= bootstrap_submit_row f %>
  <% end %>
</div><!-- product form -->

app/views/products/_product_table.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th>Donation</th>
      <!--<th></th>-->
      <!--<th></th>-->
      <th class="visible-lg-block visible-md-block"></th>

      <th>Supplier</th>
      <th>Thc</th>
      <!--<th>Cbd</th>-->
      <!--<th>Butane (ppm)</th>-->
    </tr>
    </thead>

    <tbody>
    <% products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product) %></td>
        <td><strong><%= number_to_currency(product.donation, :unit => '') %></strong></td>
        <% product.imgs.limit(1).each do |img| %>
          <td class="visible-lg-block visible-md-block">
            <%= link_to img.image.url, :target => '_blank' do %>
              <%= image_tag img.image.url(:thumb) %>
            <% end %>
          </td>
        <% end %>

        <td><%= product.supplier.name %></td>
        <td><%= display_thc(product) %></td>
        <!--<td><%= display_cbd(product) %></td>-->
        <!--<td><%= display_butane(product) %></td>-->
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/products/edit.html.erb
<div class="container">
  <div id="edit_product">
    <h1 class="page_title">Editing <%= link_to @product.name %></h1>

    <%= render 'form' %>
  </div>
</div>

app/views/products/index.html.erb
<div id="products">
  <div class="container">
    <%= quick_options(["new", new_product_path]) if user_is_admin? %>


    <% @products_hash.each do |k, v| %>
      <%= content_tag :h2, :id => k.name do %>
        <%= k.name %>
        <small>
          <%= k.description.to_s %>
        </small>
      <% end %>
      <%= render :partial => 'product_table', :locals => {:products => v} %>
    <% end %>





  </div><!-- container -->
</div><!-- products -->

app/views/products/new.html.erb
<div class="container">
  <div id="new_product">
    <h1 class="page_title">New Product</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/products/show.html.erb
<div id="product" class="container">
  <% if user_is_admin? %>
    <%= quick_options ['edit', edit_product_path(@product)], ['new', new_product_path] %>
  <% end %>
  <div class="row">
    <div class="col-sm-12">
      <h1>
        <%= @product.name %>
        <small>
          <%= @product.description.to_s %>
        </small>
      </h1>
    </div>
  </div><!-- row -->

  <div class="row">

    <div id="product_batch_info" class="col-sm-6">
      <h2>
        Batch Info
      </h2>
      <p>
        <%= @product.batch_description.to_s %>
      </p>
      <ul class="spec_list">
        <li>
          THC: <%= display_thc(@product) %>
        </li>
        <li>
          CBD: <%= display_cbd(@product) %>
        </li>
        <li>
          Butane (ppm): <%= display_butane(@product) %>
        </li>
        <li>
          <strong>
            Donation: <%= number_to_currency(@product.donation, :unit => '') %>
          </strong>
        </li>
      </ul>

      <div id="buy_product">
        <%= link_to_function 'Order', "$('#express_modal').modal('show')", :class => 'btn btn-primary' %>
      </div>
    </div><!-- col -->

    <div class="col-sm-6">
      <%# @product.imgs.each do |i| %>
        <% i = @product.imgs.sample %>
        <%= link_to i.image.url do %>
          <%= image_tag i.image.url(:gallery) %>
        <% end %>

      <%# end %>

    </div><!-- col -->

  </div>
    <!--<div class="col-sm-4"></div>-->
  <%= express_modal('Order') do %>
    <h4>We are implementing online ordering.<br><br>
      In the meantime, to place an order, call or text us at
        <%= link_to '360-670-9312', 'tel:3606709312' %> or email us at
        <%= mail_to 'jesse@medicalmarijuanavendors.com' %>.
    </h4>

  <% end %>
</div><!-- container -->

app/views/suppliers/_form.html.erb
<%= form_for(@supplier) do |f| %>
  <% if @supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% @supplier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<h1>Listing suppliers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.name %></td>
        <td><%= supplier.phone %></td>
        <td><%= supplier.email %></td>
        <td><%= supplier.user_id %></td>
        <td><%= link_to 'Show', supplier %></td>
        <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
        <td><%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supplier', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New supplier</h1>

<%= render 'form' %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supplier.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @supplier.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @supplier.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @supplier.user_id %>
</p>

<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>